package main

import (
	"bufio"
	"fmt"
	"os"
	"text/template"
)

const tmplText = `/* This file is automatically generated. */
#pragma once
#define PAK_SIZE {{.Size}}
{{- range .Entries}}
#define {{.Ident}} {{.Index}}
{{- end}}
`

func writeHeader(filename string, mn *manifest) error {
	tmpl, err := template.New("header").Parse(tmplText)
	if err != nil {
		return fmt.Errorf("could not parse template: %v", err)
	}
	fp, err := os.Create(filename)
	if err != nil {
		return err
	}
	defer fp.Close()
	wr := bufio.NewWriter(fp)
	if err := tmpl.Execute(wr, mn); err != nil {
		return fmt.Errorf("could not execute template: %v", err)
	}
	if err := wr.Flush(); err != nil {
		return err
	}
	return fp.Close()
}
