site_name: Skelly 64 Documentation
site_url: https://depp.github.io/skelly64/
repo_url: https://github.com/depp/skelly64/

markdown_extensions:
  - admonition

theme:
  name: material

nav:
  - Introduction: index.md
  - Building: building.md
  - Audio Converter: audio.md
  - Font Builder:
    - Overview: font/index.md
    - TTF Example: font/ttf_example/index.md
    - Bitmap Example: font/bitmap_example/index.md
  - Image Converter: image.md
  - Model Converter:
    - Overview: model.md
    - Format: model_format.md
  - ROM Tool: rom.md
