site_name: Skelly 64 Documentation

markdown_extensions:
  - admonition

theme:
  name: material

nav:
  - Introduction: index.md
  - Building: building.md
  - Audio Converter: audio.md
  - Font Builder: font.md
  - Image Converter: image.md
  - Model Converter:
    - Overview: model.md
  - ROM Tool: rom.md
